name: Upload code to website
on:
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  upload:
    name: Upload to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: list files
        run: ls -al
      - name: Upload code
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ FTP_SERVER }}
          username: ${{ FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
